namespace Project4Tests;

    public class BubbleSort2
    {
        //bubble sort sorting algorithm based on the pseudocode given to us by Zairul takes integer dataset as a parameter
        //from the previous functions, either a new one generated by user or one already in .txt file
        //performs bubble sorting algorithm on it, where we iterate through each value and compare it to the one in front
        //if the one we are comparing is bigger than the one in front then we swap the values, else they stay the same and
        //program iterates to the next value, etc 
        public static void PerformBubbleSort(int[] dataset)
        {

            int n = dataset.Length;

                //continuation of Zairul's pseudocode, no further additions, so just takes the pseudocode line for line

                //sets a temp variable = 0 so that it can be used later on to store a temporary value
                var temp = 0;
                //boolean value that can either be true or false, depending on if we need to do a swap or not
                bool noSwap;

                //runs while condition is not filled
                do
                {
                    noSwap = true;

                    //iterates through each element within the dataset
                    for (int i = 0; i < n - 1; i++)
                    {
                        //checks if the current value in the dataset is greater than the one that comes after
                        if (dataset[i] > dataset[i + 1])
                        {
                            //if true, then we store the current value in the temp variable
                            temp = dataset[i];
                            //swaps the current value and the one that comes next
                            dataset[i] = dataset[i + 1];
                            dataset[i + 1] = temp;
                            noSwap = false;
                        }
                    }
                } while (!noSwap);
        }
            
        }